# Generated by Django 5.2.6 on 2025-09-11 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategorier',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Navn')),
                ('description', models.TextField(blank=True, verbose_name='Beskrivelse')),
            ],
            options={
                'verbose_name': 'Udstyr',
                'verbose_name_plural': 'Udstyr',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VPID', models.CharField(max_length=100, verbose_name='VPID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Navn')),
                ('description', models.TextField(verbose_name='Beskrivelse')),
                ('location', models.CharField(blank=True, default='', max_length=100, verbose_name='Lokation')),
                ('image', models.ImageField(blank=True, upload_to='assets/', verbose_name='Billede')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='QR-kode')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('last_inspection_date', models.DateField(blank=True, help_text='Dato for seneste syn', null=True, verbose_name='Sidste synsdato')),
                ('last_service_date', models.DateField(blank=True, help_text='Dato for seneste service', null=True, verbose_name='Sidste servicedato')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.category', verbose_name='Kategori')),
                ('equipment', models.ManyToManyField(blank=True, help_text='Udstyr monteret på dette aktiv', to='assets.equipment', verbose_name='Udstyr på aktivet')),
            ],
            options={
                'verbose_name': 'Aktiv',
                'verbose_name_plural': 'Aktiver',
            },
        ),
        migrations.CreateModel(
            name='FaultReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('description', models.TextField(verbose_name='Beskrivelse (oversat)')),
                ('original_description', models.TextField(blank=True, null=True, verbose_name='Original beskrivelse')),
                ('sprog', models.CharField(choices=[('de', 'Tysk'), ('pl', 'Polsk'), ('en', 'Engelsk')], default='de', max_length=2, verbose_name='Originalt sprog')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oprettet')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Opdateret')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='Status')),
                ('qr_code', models.CharField(blank=True, default='', max_length=100, verbose_name='QR-kode')),
                ('image', models.ImageField(blank=True, upload_to='fault_reports/', verbose_name='Billede')),
                ('repair_status', models.BooleanField(default=False, verbose_name='Reparationsstatus')),
                ('machine', models.CharField(blank=True, default='', max_length=100, verbose_name='Maskine')),
                ('location', models.CharField(blank=True, default='', max_length=100, verbose_name='Lokation')),
                ('vpid', models.CharField(blank=True, max_length=100, verbose_name='VPID')),
                ('priority', models.IntegerField(choices=[(1, 'Høj'), (2, 'Normal'), (3, 'Lav (vent til service)')], default=2, verbose_name='Prioritet')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Arbejde påbegyndt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Afsluttet')),
                ('notes', models.TextField(blank=True, verbose_name='Noter (til mekaniker)')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Godkendt')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset', verbose_name='Aktiv')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL, verbose_name='Tildelt mekaniker')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_reports', to=settings.AUTH_USER_MODEL, verbose_name='Udført af')),
            ],
            options={
                'verbose_name': 'Fejlrapport',
                'verbose_name_plural': 'Fejlrapporter',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
