# Generated by Django 5.2.5 on 2025-09-01 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategorier',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Navn', models.CharField(max_length=100, verbose_name='Navn')),
                ('Beskrivelse', models.TextField(blank=True, verbose_name='Beskrivelse')),
            ],
            options={
                'verbose_name': 'Udstyr',
                'verbose_name_plural': 'Udstyr',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VPID', models.CharField(max_length=100, verbose_name='VPID')),
                ('description', models.TextField(verbose_name='Beskrivelse')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Navn')),
                ('location', models.CharField(blank=True, default='', max_length=100, verbose_name='Lokation')),
                ('title_en', models.CharField(blank=True, default='', max_length=100, verbose_name='Titel (EN)')),
                ('description_en', models.TextField(blank=True, default='', verbose_name='Beskrivelse (EN)')),
                ('title_de', models.CharField(blank=True, default='', max_length=100, verbose_name='Titel (DE)')),
                ('description_de', models.TextField(blank=True, default='', verbose_name='Beskrivelse (DE)')),
                ('title_pl', models.CharField(blank=True, default='', max_length=100, verbose_name='Titel (PL)')),
                ('description_pl', models.TextField(blank=True, default='', verbose_name='Beskrivelse (PL)')),
                ('image', models.ImageField(blank=True, upload_to='assets/', verbose_name='Billede')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Aktiv',
                'verbose_name_plural': 'Aktiver',
            },
        ),
        migrations.CreateModel(
            name='FaultReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('description', models.TextField(verbose_name='Beskrivelse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oprettet')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='Status')),
                ('qr_code', models.CharField(blank=True, default='', max_length=100, verbose_name='QR-kode')),
                ('image', models.ImageField(blank=True, upload_to='fault_reports/', verbose_name='Billede')),
                ('repair_status', models.BooleanField(default=False, verbose_name='Reparationsstatus')),
                ('machine', models.CharField(blank=True, default='', max_length=100, verbose_name='Maskine')),
                ('location', models.CharField(blank=True, default='', max_length=100, verbose_name='Lokation')),
                ('vpid', models.CharField(blank=True, max_length=100, verbose_name='VPID')),
                ('priority', models.IntegerField(choices=[(1, 'Høj'), (2, 'Normal'), (3, 'Lav (vent til service)')], default=2, verbose_name='Prioritet')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset', verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Fejlrapport',
                'verbose_name_plural': 'Fejlrapporter',
            },
        ),
    ]
