# Generated by Django 5.2.6 on 2025-09-16 07:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Kategorier'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name_plural': 'Udstyr'},
        ),
        migrations.AlterModelOptions(
            name='faultreport',
            options={},
        ),
        migrations.AddField(
            model_name='asset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oprettet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Opdateret'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.category', verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='mechanic_report',
            field=models.TextField(blank=True, null=True, verbose_name='Mekanikerrapport'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='VPID',
            field=models.CharField(max_length=50, unique=True, verbose_name='VPID'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beskrivelse'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='assets.equipment', verbose_name='Tilknyttet udstyr'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='in_workshop',
            field=models.BooleanField(default=False, verbose_name='I værksted'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='last_inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sidste syn'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='last_service_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sidste service'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100, verbose_name='Lokation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='qr_code',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100, verbose_name='QR-kode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='workshop_from_date',
            field=models.DateField(blank=True, null=True, verbose_name='Værksted fra'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Kategorinavn'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='Navn',
            field=models.CharField(max_length=100, verbose_name='Udstyrsnavn'),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='status',
            field=models.CharField(choices=[('Active', 'Aktiv'), ('Paused', 'På pause'), ('Completed', 'Afsluttet')], default='Active', max_length=20, verbose_name='Status'),
        ),
    ]
