# Generated by Django 5.2.6 on 2025-09-11 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
    ]
