# Generated by Django 5.2.5 on 2025-09-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_qr_code_alter_asset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
    ]
