# Generated by Django 5.2.6 on 2025-09-22 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faultreport',
            name='qr_code',
        ),
    ]
