# Generated by Django 5.2.6 on 2025-09-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_faultreport_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultreport',
            name='expected_workshop_date',
            field=models.DateTimeField(blank=True, help_text='Dato og tid for når aktivet forventes indkaldt til værksted.', null=True, verbose_name='Forventet indkaldelse til værksted'),
        ),
    ]
