# Generated by Django 5.2.5 on 2025-09-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='description_pl',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='title_pl',
        ),
        migrations.AddField(
            model_name='asset',
            name='equipment',
            field=models.ManyToManyField(blank=True, help_text='Udstyr monteret på dette aktiv', to='assets.equipment', verbose_name='Udstyr på aktivet'),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_inspection_date',
            field=models.DateField(blank=True, help_text='Dato for seneste syn', null=True, verbose_name='Sidste synsdato'),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_service_date',
            field=models.DateField(blank=True, help_text='Dato for seneste service', null=True, verbose_name='Sidste servicedato'),
        ),
    ]
