# Generated by Django 5.2.5 on 2025-09-02 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_asset_description_de_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faultreport',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'Fejlrapport', 'verbose_name_plural': 'Fejlrapporter'},
        ),
        migrations.AddField(
            model_name='faultreport',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL, verbose_name='Tildelt mekaniker'),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Afsluttet'),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_reports', to=settings.AUTH_USER_MODEL, verbose_name='Udført af'),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Godkendt'),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Noter (til mekaniker)'),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arbejde påbegyndt'),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Opdateret'),
        ),
    ]
