# Generated by Django 5.2.5 on 2025-09-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_faultreport_options_faultreport_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultreport',
            name='original_description',
            field=models.TextField(blank=True, null=True, verbose_name='Original beskrivelse'),
        ),
    ]
